# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# Book settings
title: Spark Data Frame Programming for Modern Data Engineering 
author: Deepak Gowda
logo: images/sparklogo.png
exclude_patterns: ["cache"]

latex:
  latex_documents:
    targetname: book.tex
    
launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url     : "https://mybinder.org"
  thebe             : true

sphinx:
  extra_extensions:
    - sphinx_thebe

repository:
  url          : https://github.com/ngdeepak/testbook  # The URL to your book's repository
  path_to_book : ""  # A path to your book's folder, relative to the repository root.
  branch       : master  # Which branch of the repository should be used when creating links
  
html:
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: "https://www.miningmassivedata.com/testbook/"
